backend/apps/albums/urls.py
from django.urls import path

from apps.albums.views import ImageListView, ImageUploadView

app_name = "albums"

urlpatterns = [
    path("", ImageListView.as_view(), name="list"),
    path("upload", ImageUploadView.as_view(), name="upload"),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("accounts/", include("apps.accounts.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("albums/", include("apps.albums.urls")),
    path("blogs/", include("apps.blogs.urls")),
    path("diaries/", include("apps.diaries.urls")),
    path("maps/", include("apps.maps.urls")),
    path("lotteries/", include("apps.lotteries.urls")),
    path("poker-face/", include("poker_face.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

backend/apps/albums/models.py
from django.db import models
from django.utils import timezone


def origin_path(instance, filename):
    time_now = timezone.now().astimezone()
    date = time_now.date().strftime("%y%m%d")
    time = time_now.strftime("%H%M%S")
    origin_path = f"images/{date}/{time}/{filename}"
    return origin_path


class Image(models.Model):
    created_at = models.DateTimeField()
    origin = models.ImageField(upload_to=origin_path)
    caption = models.CharField(max_length=255, null=True, blank=True)
    people = models.ManyToManyField("albums.Person", through="albums.ImagePerson")
    events = models.ManyToManyField("albums.Event", through="albums.ImageEvent")


class Person(models.Model):
    name = models.CharField(max_length=30)


class ImagePerson(models.Model):
    image = models.ForeignKey("albums.Image", on_delete=models.PROTECT)
    person = models.ForeignKey("albums.Person", on_delete=models.PROTECT)


class Event(models.Model):
    date = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=100)


class ImageEvent(models.Model):
    image = models.ForeignKey("albums.Image", on_delete=models.PROTECT)
    event = models.ForeignKey("albums.Event", on_delete=models.PROTECT)

backend/apps/albums/views.py
from django.conf import settings
from django.db import transaction
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.http import urlencode
from django.views.generic import TemplateView

from apps.albums.models import Image
from apps.albums.query import get_image_data, get_people_data
from apps.albums.serialize import image_serializer, page_serializer, person_serializer


class ImageUploadView(TemplateView):
    template_name = "albums/upload.html"

    def post(self, request, *args, **kwargs):
        time_now = timezone.now().astimezone()
        image_origin = self.request.FILES.get("image_origin")
        caption = self.request.POST.get("caption")
        people = self.request.POST.get("people", "")
        people_list = list(map(lambda x: x.strip(), people.split(",")))
        people_set = get_people_data()
        image_people_list = []
        for person_name in people_list:
            for person in people_set:
                if person_name == person.name:
                    image_people_list.append(person.id)
        with transaction.atomic():
            image = Image(created_at=time_now, origin=image_origin, caption=caption)
            image.save()
            for person in image_people_list:
                image.people.add(person)
        return redirect("albums:list")


class ImageListView(TemplateView):
    template_name = "albums/main.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        page = int(self.request.GET.get("page", 1))
        limit = int(self.request.GET.get("limit", 6))
        person = self.request.GET.get("person", "")
        image_set = get_image_data(person)
        image_count = image_set.count()
        paged_image_set = image_set[(page - 1) * limit : page * limit]
        people_set = get_people_data()
        context_data["is_test"] = settings.DEBUG
        context_data["person"] = person
        context_data["data"] = [image_serializer(image) for image in paged_image_set]
        context_data["people"] = [person_serializer(person) for person in people_set]
        context_data["page"] = page_serializer(page, limit, person, image_count)
        return context_data

backend/templates/albums/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Album</title>
{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/albums/main.css' %}">
{% endblock stylesheet %}

{% block javascript %}
  <script src="{% static 'js/libraries/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/albums/main.js' %}"></script>
{% endblock javascript %}

{% block content %}
<div class="container">
  {% include "albums/upload-modal.html" %}
  <div class="mt-3 albums-header">
    <div class="title-area">
      <div class="h1">
        Album
      </div>
      {% if person != "" %}
      <div class="mx-2 h6">
        for {{ person }}
      </div>
      {% endif %}
    </div>
    <div class="command-area">
      <div class="mx-2 dropdown">
        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">
          멤버 선택
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'albums:list' %}">전체</a></li>
        {% for person in people %}
          <li><a class="dropdown-item" href="{% url 'albums:list' %}?person={{ person.name }}">{{ person.name }}</a></li>
        {% endfor %}
        </ul>
      </div>
      <button class="mx-2 btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#imageUploadModal">
        사진 등록
      </button>
    </div>
  </div>
  <div class="mt-3 p-2 image-area">
    {% for image in data%}
      <div class="m-2 image-container">
        <div class="image-item">
          <img src="{{ image.origin }}" alt="image" class="image"/>
          {% if image.caption != "" %}
            <div class="caption">{{ image.caption }}</div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="m-3 page-bar">
    <div class="page-prev">
      {% if page.prev != ""%}
      <button class="btn btn-secondary btn-sm" type="button" onclick="window.location.href='{% url 'albums:list' %}{{ page.prev }}'">
        <
      </button>
      {% endif %}
    </div>
    <div class="page-current">
      - {{ page.current }} - 
    </div>
    <div class="page-next">
      {% if page.next != ""%}
      <button class="btn btn-secondary btn-sm" type="button" onclick="window.location.href='{% url 'albums:list' %}{{ page.next }}'">
        >
      </button>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

backend/templates/albums/upload-modal.html
<div class="modal fade" id="imageUploadModal" data-bs-keyboard="false" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form method="post" action="{% url 'albums:upload' %}" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="modal-header">
          <h1 class="modal-title fs-5">사진 등록</h1>
        </div>
        <div class="modal-body">
          <div class="input-field">
            <i class='bx bx-image-add'></i>
            <input class="image-input" type="file" accept=".jpg .png" name="image_origin" required/>
          </div>
          <div class="input-field">
            <i class='bx bx-text'></i>
            <input class="caption-input" type="text" name="caption" placeholder="사진 이름"/>
          </div>
          <div class="select-field">
            <i class='bx bxs-group'></i>
            <div class="select-container">
              <select class="select-box" multiple> 
                {% for person in people %}
                  <option value="person-{{ person.id }}">{{ person.name }}</option>
                {% endfor %}
              </select>
              <button id="add-person" type="button" class="btn btn-secondary btn-sm">적용</button>
              <div id="selected-options"></div>
              <input id="selected-options-input" type="hidden" name="people"/>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">업로드</button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/templates/albums/upload.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Album</title>
{% endblock title %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data" class="m-3">
  {% csrf_token %}
  <div class="m-2">
    image: <input type="file" accept="img/*" name="image_origin"/>
  </div>
  <div class="m-2">
    caption: <input type="text" name="caption"/>
  </div>
  <div class="m-2">
    people: <input type="text" name="people"/>
  </div>
  <button type="submit">사진 업로드</button>
</form>
{% endblock content %}