backend/apps/blogs/urls.py
from django.urls import path

from apps.blogs.views import BlogCreateView, BlogDetailView, BlogMainView, StudyView

app_name = "blogs"


urlpatterns = [
    path("", BlogMainView.as_view(), name="main"),
    path("write", BlogCreateView.as_view(), name="write"),
    path("study/<str:study_name>/", StudyView.as_view(), name="study"),
    path("<int:post_id>", BlogDetailView.as_view(), name="detail"),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("accounts/", include("apps.accounts.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("albums/", include("apps.albums.urls")),
    path("blogs/", include("apps.blogs.urls")),
    path("diaries/", include("apps.diaries.urls")),
    path("maps/", include("apps.maps.urls")),
    path("lotteries/", include("apps.lotteries.urls")),
    path("poker-face/", include("poker_face.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

backend/apps/blogs/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# class Subcategory(models.Model):
#     name = models.CharField(max_length=255)


# class Category(models.Model):
#     name = models.CharField(max_length=255)
#     sub_category = models.ForeignKey(Subcategory)


class Post(models.Model):
    created_at = models.DateTimeField()
    title = models.CharField(max_length=255)
    content = RichTextUploadingField(null=True, blank=True)
    # category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)


# 분류 모델
# class Category
# class Subcategory
# class Subtype

backend/apps/blogs/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from apps.blogs.widgets import TextInput
from apps.blogs.models import Post


# class PostForm(forms.ModelForm):
class PostForm(forms.Form):
    title = forms.CharField(widget=TextInput())
    content = forms.CharField(widget=CKEditorWidget())
    # class Meta:
    #     model = Post
    #     fields = ["title", "content"]

backend/apps/blogs/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView

from apps.blogs.forms import PostForm
from apps.blogs.models import Post


class StudyView(TemplateView):
    def get_template_names(self):
        template_name = f"blogs/study/{self.kwargs.get('study_name')}.html"
        return template_name


class BlogMainView(TemplateView):
    template_name = "blogs/main.html"


class BlogCreateView(View):
    template_name = "blogs/write.html"
    form_class = PostForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        time_now = timezone.now().astimezone()
        if form.is_valid():
            post = Post(created_at=time_now, **form.cleaned_data)
            post.save()
            url = reverse("blogs:detail", kwargs={"post_id": post.id})
            return redirect(url)

        return render(request, self.template_name, {"form": form})


class BlogDetailView(TemplateView):
    template_name = "blogs/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs.get("post_id")
        context["blog"] = Post.objects.get(id=post_id)
        return context

backend/templates/blogs/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Blog</title>
{% endblock title %}

{% block content %}
<div class="m-3 conatiner">
  <h1> {{blog.title}} </h1>
  <br>
  <p> {{blog.created_at}} </p>
  <p> {{blog.content|safe}} </p>
</div>
{% endblock content %}

backend/templates/blogs/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Blog</title>
{% endblock title %}

{% block content %}
<div class="m-3 container">
  <h1>Blog Main Page</h1>
  <div class="m-3">
    <div class="m-3" style="display:inline;">글 작성하러 가기</div>
    <button>
      <a href="{% url 'blogs:write' %}">새 글</a>
    </button>
  </div>
</div>
{% endblock content %}

backend/templates/blogs/write.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Blog</title>
{% endblock title %}

{% block content %}
<div class="m-3 container">
  <form method ="post">
    {% csrf_token %}
    {{ form.media }}    
    {{ form.as_p }}
    <input type="submit" value="작성하기">
  </form>
</div>
{% endblock content %}