backend/apps/accounts/urls.py
from apps.accounts.views import LoginView, SignupView
from django.urls import path

app_name = "accounts"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("accounts/", include("apps.accounts.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("albums/", include("apps.albums.urls")),
    path("blogs/", include("apps.blogs.urls")),
    path("diaries/", include("apps.diaries.urls")),
    path("maps/", include("apps.maps.urls")),
    path("lotteries/", include("apps.lotteries.urls")),
    path("poker-face/", include("poker_face.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

backend/apps/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def get_by_natural_key(self, username):
        return self.get(username=username)

    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("The Username field must be set")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(username, password, **extra_fields)


class User(PermissionsMixin, AbstractBaseUser):
    created_at = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=150)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "username"


class UserType(models.Model):
    code = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=150, blank=True, null=True)


class UserTypeAssignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user", "user_type")

backend/apps/accounts/views.py
from apps.accounts.models import User, UserType, UserTypeAssignment
from django.contrib.auth import authenticate
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken


@method_decorator(csrf_exempt, name="dispatch")
class SignupView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        username = request.data.get("username")
        password = request.data.get("password")
        name = request.data.get("name")
        phone = request.data.get("phone")
        email = request.data.get("email")
        user_type = request.data.get("userType")

        if User.objects.filter(username=username).exists():
            return Response(
                {"error": f"사용자({username})가 이미 존재합니다."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if not (user_type and UserType.objects.filter(code=user_type).exists()):
            return Response(
                {"error": "유효하지 않은 가입 코드입니다."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        user = User(username=username, name=name, email=email, phone=phone)
        user.set_password(password)
        user.save()
        user_type = UserType.objects.get(code=user_type)
        UserTypeAssignment.objects.create(user=user, user_type=user_type)
        return Response({"message": "회원가입 완료"}, status=status.HTTP_201_CREATED)


@method_decorator(csrf_exempt, name="dispatch")
class LoginView(APIView):
    def post(self, request):
        username = request.data.get("username")
        password = request.data.get("password")

        user = authenticate(username=username, password=password)

        if user is None:
            return Response(
                {"error": "잘못된 인증 정보입니다."},
                status=status.HTTP_401_UNAUTHORIZED,
            )

        user_type_assignment = (
            UserTypeAssignment.objects.filter(user_id=user.id)
            .select_related("user_type")
            .last()
        )

        if user_type_assignment is None:
            return Response(
                {"error": "사용자 정보를 찾을 수 없습니다."},
                status=status.HTTP_401_UNAUTHORIZED,
            )

        match user_type_assignment.user_type.code:
            case "pokerface":
                next_url = "/poker-face/"
            case _:
                next_url = "/"

        refresh = RefreshToken.for_user(user)
        return Response(
            {
                "access": str(refresh.access_token),
                "refresh": str(refresh),
                "next": next_url,
            }
        )

backend/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Login</title>
{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts/main.css' %}">
{% endblock stylesheet %}

{% block content %}
<div class="wrapper">
  <h1>로그인</h1>
  <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <div class="input-box">
      <div class="input-field">
        <input type="text" name="username" placeholder="Username (ID)" required>
        <i class='bx bxs-user'></i>
      </div>
      <div class="input-field">
        <input type="password" name="password" placeholder="Password" onkeyup="checkCapsLock(event)" required>
        <i class='bx bxs-lock-alt'></i>
        <div id="messageCapsLock"></div>
      </div>
    </div>
    <button type="submit" class="submit-btn">Login</button>
  </form>
</div>
{% endblock content %}

backend/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>SignUp</title>
{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts/main.css' %}">
{% endblock stylesheet %}

{% block content %}
<div class="wrapper">
  <h1>계정 등록</h1>
  <form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    <div class="input-box">
      <div class="input-field">
        <input type="text" name="name" placeholder="Name" required>
        <i class='bx bxs-user'></i>
      </div>
      <div class="input-field">
        <input type="text" name="username" placeholder="Username (ID)" required>
        <i class='bx bxs-user'></i>
      </div>
      {% comment %} <div class="input-field">
        <input type="text" name="email" placeholder="Email" required>
        <i class='bx bxs-envelope'></i>
      </div>
      <div class="input-field">
        <input type="tel" name="phone" placeholder="Phone Number" required>
        <i class='bx bxs-phone'></i>
      </div> {% endcomment %}
      <div class="input-field">
        <input type="password" name="password" placeholder="Password" onkeyup="checkCapsLock(event)" required>
        <i class='bx bxs-lock-alt'></i>
        <div id="messageCapsLock"></div>
      </div>
      <div class="input-field">
        <input type="password" name="passwordC" placeholder="Password 확인" required>
        <i class='bx bxs-lock-alt'></i>
      </div>
    </div>
    <label>
      <input type="checkbox" required> 위 정보로 가입을 동의합니다.
    </label>
    <button type="submit" class="submit-btn">Register</button>
  </form>
</div>
{% endblock content %}